### ISSUE TITLE
DatabaseSequence bug leads to following exception

### ISSUE THREAD

**Issue by ijazfx** [wocommunity/wonder#587]
<pre>
2014-03-17 16:28:09,853 ERROR APPNAME[-:12345 1] VisaApplicationProcessNumber (ERXSequence.java:208)  - org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
 org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.setReadOnly(AbstractJdbc2Connection.java:725)
	at er.extensions.eof.ERXSequence$DatabaseSequence.increasedMaxValue(ERXSequence.java:206)
	at er.extensions.eof.ERXSequence$DatabaseSequence.<init>(ERXSequence.java:137)
	at er.extensions.eof.ERXSequence$DatabaseSequence.<init>(ERXSequence.java:142)
	at er.extensions.eof.ERXSequence.createDatabaseSequenceWithName(ERXSequence.java:309)
	...
</pre>

**Comment by darkv** [comment]
This issue has already been fixed.
