### ISSUE TITLE
IllegalStateException thrown from ProcessChangesQueue.stop() can prevent termination

### ISSUE THREAD

**Issue by paulhoadley** [wocommunity/wonder#784]
Ted Archibald first [noted this on the mailing list](http://lists.apple.com/archives/webobjects-dev/2013/Nov/msg00159.html) in December 2013:

> The stack trace points to an error in ERXObjectStoreCoordinatorSynchronizer$ProcessChangesQueue.stop "Attempted to stop the ProcessChangesQueue when it wasn't already running".  I don't really care about that error, I just want the instance to shut down, but this stops the normal shutdown process.

Here's the relevant part of the stack trace:

    Caused by: java.lang.IllegalStateException: Attempted to stop the ProcessChangesQueue when it wasn't already running
        at er.extensions.eof.ERXObjectStoreCoordinatorSynchronizer$ProcessChangesQueue.stop(ERXObjectStoreCoordinatorSynchronizer.java:618)
        at er.extensions.eof.ERXObjectStoreCoordinatorSynchronizer.stopRemoteSynchronizer(ERXObjectStoreCoordinatorSynchronizer.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    ...
        at com.webobjects.foundation.NSNotificationCenter.postNotification(NSNotificationCenter.java:532)
        at com.webobjects.foundation.NSNotificationCenter.postNotification(NSNotificationCenter.java:546)
        at er.extensions.appserver.ERXApplication.terminate(ERXApplication.java:2733)
        at com.webobjects.appserver.WOApplication._terminateFromMonitor(WOApplication.java:3607)
    ...

I’ve just seen this as well, though I can’t reliably reproduce it. This is the code:

    public void stop() {
        if (_queueThread != null && _queueThread.isAlive()) {
            _running = false;
            _queueThread.interrupt();
        }
        else {
            throw new IllegalStateException("Attempted to stop the " + getClass().getSimpleName() + " when it wasn't already running");
        }
    }

I’m not seeing the rationale for throwing an exception here. This is being called when `ERXApplication.ApplicationWillTerminateNotification` is posted. If `_queueThread` is `null` or not alive, couldn’t we just do nothing and log it? There’s nothing catching this exception, and it goes on to prevent termination, as Ted notes.

Note that although Ted and I both saw this in the context of using `ERJGroupsSynchronizer`, this is a problem specifically with `ERXObjectStoreCoordinatorSynchronizer`. `ERJGroupsSynchronizer` seems to shut itself down without issue using `ERXShutdownHook`.

**Comment by darkv** [comment]
fixed by merged #785

**Comment by paulhoadley** [comment]
Thanks @darkv.
