### ISSUE TITLE
WONDER-711 ERMDDeleteButton throws exception when deleting newly created object 

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#89]
Reported by Freddie Tilley

After creating a new relationship eo object for an object in ERModernLook D2W using the embedded ERMODEditRelationshipPage. When trying to delete the newly created relationship object without saving the parent object first throws the following exception: 

NullPointerException 
  at er.modern.directtoweb.components.buttons.ERMDDeleteButton.deleteObjectWithFinalCommit(ERMDDeleteButton.java:127) 
  at er.modern.directtoweb.components.buttons.ERMDDeleteButton.deleteAction(ERMDDeleteButton.java:107) 
     ... skipped 14 stack elements 
  at er.ajax.AjaxUpdateLink.handleRequest(AjaxUpdateLink.java:383) 
     ... skipped 184 stack elements 
  at er.ajax.AjaxRequestHandler.handleRequest(AjaxRequestHandler.java:17) 
  ... skipped 6 stack elements 

It appears that in the code 

if (finalCommit) { // if we are editing, then don't save the parent ec. 
object().editingContext().saveChanges(); 
} 

the newly created object() does not have an editing context.

**Comment by fbarthez** [comment]
This was fixed in d0ee79f8248a7d455b67519f7a83ec86bf8f195b.

**Comment by darkv** [comment]
Thanks for your hint!
