### ISSUE TITLE
WOInstaller crash

### ISSUE THREAD

**Issue by andreipokotskiy** [wocommunity/wonder#911]
wget https://jenkins.wocommunity.org/job/WOInstaller/lastSuccessfulBuild/artifact/Utilities/WOInstall/WOInstaller.jar
java -jar WOInstaller.jar 5.4.3 /opt
WebObjects License Agreement extract:

Subject to the terms and conditions of this License, you may incorporate the
WebObjects Software included in the Developer Software into application
programs (both client and server) that you develop on an Apple-branded
computer. You may also reproduce and distribute the WebObjects Software
unmodified, in binary form only, on any platform but solely as incorporated
into such application programs and only for use by end-users under terms that
are at least as restrictive of those set forth in this License (including,
without limitation, Sections 2, 6 and 7 of this License).

For avoidance of doubt, you may not distribute the WebObjects Software on a
stand-alone basis, and you may not develop application programs using the
WebObjects Software (or any portion thereof) on any non-Apple branded
computer.

Exception in thread "main" java.io.IOException: Expected magic '070707' but got '�' (next = �����������������).
        at er.woinstaller.archiver.CPIO.extractTo(Unknown Source)
        at er.woinstaller.WebObjectsInstaller.installToFolder(Unknown Source)
        at er.woinstaller.Main.main(Unknown Source)

And for lastStableBuild
java -jar WOInstaller.jar 5.4.3 /opt
WebObjects License Agreement extract:

Subject to the terms and conditions of this License, you may incorporate the
WebObjects Software included in the Developer Software into application
programs (both client and server) that you develop on an Apple-branded
computer. You may also reproduce and distribute the WebObjects Software
unmodified, in binary form only, on any platform but solely as incorporated
into such application programs and only for use by end-users under terms that
are at least as restrictive of those set forth in this License (including,
without limitation, Sections 2, 6 and 7 of this License).

For avoidance of doubt, you may not distribute the WebObjects Software on a
stand-alone basis, and you may not develop application programs using the
WebObjects Software (or any portion thereof) on any non-Apple branded
computer.

Extracting WebObjects ...: Done                                           
Exception in thread "main" java.io.IOException: Failed to delete '/opt.
        at er.woinstaller.WebObjectsInstallation.renameFolders(Unknown Source)
        at er.woinstaller.WebObjectsInstallation.<init>(Unknown Source)
        at er.woinstaller.WebObjectsInstaller.installToFolder(Unknown Source)
        at er.woinstaller.Main.main(Unknown Source)

**Comment by rkiddy** [comment]
Hm. What kids of system and OS are you trying this on?

I created a new AWS instance (Ubuntu Server 18.04 LTS) and ran it and got a different error.

     $ sudo  java -jar WOInstaller.jar 5.4.3 /opt
     WebObjects License Agreement extract:
     
     Subject to the terms and conditions of this License, you may incorporate the
     WebObjects Software included in the Developer Software into application
     programs (both client and server) that you develop on an Apple-branded
     computer. You may also reproduce and distribute the WebObjects Software
     unmodified, in binary form only, on any platform but solely as incorporated
     into such application programs and only for use by end-users under terms that
     are at least as restrictive of those set forth in this License (including,
     without limitation, Sections 2, 6 and 7 of this License).
     
     For avoidance of doubt, you may not distribute the WebObjects Software on a
     stand-alone basis, and you may not develop application programs using the
     WebObjects Software (or any portion thereof) on any non-Apple branded
     computer.
     
     
     Exception in thread "main" java.util.zip.ZipException: Not in GZIP format
     	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
     	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
     	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
     	at er.woinstaller.WebObjectsInstaller.getInputStream(Unknown Source)
     	at er.woinstaller.WebObjectsInstaller.installToFolder(Unknown Source)
     	at er.woinstaller.Main.main(Unknown Source)

**Comment by andreipokotskiy** [comment]
It was on Ubuntu 16.04.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial


I couldn't  run WOInstaller downloaded from https://jenkins.wocommunity.org/job/WOInstaller/lastSuccessfulBuild/artifact/Utilities/WOInstall/WOInstaller.jar. Then I downloaded it from  https://jenkins.wocommunity.org/job/WOInstaller/lastStableBuild/artifact/Utilities/WOInstall/WOInstaller.jar, and installation was almost completed. Only at the end of installation I got an error that installer couldn't delete some empty folder.

**Comment by rkiddy** [comment]
Hm. And I downloaded the WOInstaller.jar on my Mac and ran it and it finished with no errors.

Perhaps something got fixed? Some magic happened?

@andreipokotskiy What are you seeing?

**Comment by paulhoadley** [comment]
For what it's worth, I can reproduce the `Expected magic '070707'` with `lastStableBuild` and `Not in GZIP format` with `lastSuccessfulBuild`.

This is going to need someone that cares about WOInstaller to adopt it.

**Comment by timoteoponce** [comment]
The installer fails for me too, but the following step taken from https://wiki.wocommunity.org/display/WEB/Project+Wonder+Installation did the trick:

```
If you already have the WebObjects543.dmg or the automatic download does not works use this variant:

curl -O -L https://download.info.apple.com/Mac_OS_X/061-4634.20080915.3ijd0/WebObjects543.dmg

cp WebObjects543.dmg /tmp/

sudo java -jar WOInstaller.jar dev54 /opt
```

**Comment by timcu** [comment]
@timoteoponce 's solution fixes the first problem. The second problem only occurs on Linux and Windows. I have fixed it with #997

**Comment by ion497** [comment]
I ran into this same issue and had to build the WOInstaller.jar utility myself to get @timcu's fix:

```
curl -O -L https://download.info.apple.com/Mac_OS_X/061-4634.20080915.3ijd0/WebObjects543.dmg
cp WebObjects543.dmg /tmp/
git clone https://github.com/wocommunity/wonder.git
cd wonder/Utilities/WOInstall
ant build
sudo mkdir -p /opt/WebObjects
sudo java -jar WOInstaller.jar dev54 /opt/WebObjects
```
